# Generated by Django 4.0.3 on 2024-08-14 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0006_answer_votor_question_votor_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votor',
        ),
        migrations.RemoveField(
            model_name='question',
            name='votor',
        ),
        migrations.AddField(
            model_name='answer',
            name='votoer',
            field=models.ManyToManyField(related_name='voter_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='voter',
            field=models.ManyToManyField(related_name='voter_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
