# Generated by Django 4.0.3 on 2024-08-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_remove_answer_votor_remove_question_votor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='votoer',
            new_name='voter',
        ),
    ]
